import numpy as np
import cv2 as cv
from matplotlib import pyplot as plt
img = cv.imread('visage.jpeg')
img_adv = cv.imread('adventure.jpeg')
# edges2 = cv.Canny(img,200,200)
# edges3 = cv.Canny(img,200,300)
laplacian = cv.Laplacian(img_adv,cv.CV_64F)
sobelx = cv.Sobel(img,cv.CV_64F,1,0,ksize=5)
sobely = cv.Sobel(img,cv.CV_64F,0,1,ksize=5)

edges4 = cv.Canny(img_adv,200,400)
kernel = np.ones((4,4),np.uint8)
edge_dilate = cv.dilate(edges4,kernel, iterations=1)
# edges5 = cv.Canny(img,200,500)
# edges6 = cv.Canny(img,200,600)
# edges7 = cv.Canny(img,200,700)
# edges_adv = cv.Canny(img_adv,200,300)
# cv.imshow("edges2", edges2)
# cv.imshow("edges3", edges3)
cv.imshow("edges4", edges4)
cv.imshow("edge_dilate", edge_dilate)
cv.imshow("laplacian", laplacian)
cv.imshow("sobelx", sobelx)
cv.imshow("sobely", sobely)
# cv.imshow("edges5", edges5)
# cv.imshow("edges6", edges6)
# cv.imshow("edges7", edges7)
# cv.imshow("img_adv", edges_adv)
cv.waitKey(0)
cv.destroyAllWindows()
#
# plt.subplot(121),plt.imshow(img,cmap = 'gray')
# plt.title('Original Image'), plt.xticks([]), plt.yticks([])
# plt.subplot(122),plt.imshow(edges,cmap = 'gray')
# plt.title('Edge Image'), plt.xticks([]), plt.yticks([])
# plt.show()